### ISSUE TITLE
How to clear or delete saved preference?

### ISSUE THREAD

**Issue by ashish1988** [skydoves/ColorPickerPreference#1]
How can I clear the saved preference as I need to clear it after log out and need to set default colour for new user.

**Comment by skydoves** [comment]
It's not exist of clear methods. but you can set default color like this:
```java
ColorPickerSharedPreferencesManager preferencesManager = new ColorPickerSharedPreferencesManager(mContext);
preferencesManager.putInteger("YOUR_COLORPICKER_NAME" + ColorPickerSharedPreferencesManager.COLOR, Color.WHITE);
```

**Comment by ashish1988** [comment]
Thank you for replying :). If I can't clear preference then it's creation is useless.
Can you tell me how to set a colour to ColorPickerView? I will manage it by app's preference if I could set a colour to it. Please suggest.

**Comment by skydoves** [comment]
I think it seems to need clears saved preferences and sets a color to ColorPickerView methods. 
I will add it soon. :) Thank you for your Issue!

**Comment by skydoves** [comment]
it released at v1.0.3!
You can set saved color using below method.
```java
colorPickerView.setSavedColor(YOUR_COLOR);
```
And can clear all of saved data using like this
```java
colorPickerView.clearSavedData();
```

**Comment by ashish1988** [comment]
Many thanks @skydoves. I just want to confirm would this method (colorPickerView.setSavedColor(YOUR_COLOR);) put the pointer to the colour location on the picker?

**Comment by skydoves** [comment]
not yet. I think it seems to need an algorithm like finding the color position from an image.
for example the following image,

![palettebar](https://user-images.githubusercontent.com/24237865/37238578-d2c66964-246c-11e8-8d48-de6cc62f53eb.jpg)

how do you think what is the best position for color red?
