### ISSUE TITLE
The selector is not displayed in the upper, lower, left and right positive directions.

### ISSUE THREAD

**Issue by dtboy1995** [skydoves/ColorPickerPreference#12]
First of all, thanks to the author
- screen shot
![screen](https://muqi.oss-cn-beijing.aliyuncs.com/error1.jpg?x-oss-process=style/sq-300)

**Comment by skydoves** [comment]
@dtboy1995 
Sorry for the late reply. 
It is solved on this [library](https://github.com/skydoves/ColorPickerView).
Thakn you for your issue!
