### ISSUE TITLE
Selector is completely invisible!

### ISSUE THREAD

**Issue by forgottenrip** [skydoves/ColorPickerPreference#13]
Hi Skydoves,
The selector (wheel) or every drawable I choose is invisible in version 1.0.3 - 1.0.6
It happened exactly after (colorpickerpreference:1.0.2).
Ver 1.0.2 is the latest working release.
meanwhile my problem with 1.0.2 is incompatibility with android 9.0

**Comment by skydoves** [comment]
@forgottenrip 
Hi, sorry for late reply.
Can you explain more details?
Do you mean the selector being invisible when you change the palette drawable?
