### ISSUE TITLE
Why not support ARGB?

### ISSUE THREAD

**Issue by Blankeer** [skydoves/ColorPickerPreference#2]
It only support `HSV color, RGB values`, right?
Why not support `ARGB`?
thx.

**Comment by skydoves** [comment]
I wanted just simplification.
There are many other colorPicker libraries support ARGB.
But it looks more complicated and feels being in the box. 
Generally, in IoT [projects](https://github.com/skydoves/MagicLight-Controller), communication protocols have Brightness control Attribute.
So ARGB does not need in other cases.
Implementing  ARGB is really easy. so I chose expandability.
But after reading this [article](https://blog.stylingandroid.com/colour-wheel-part-1/), I'm considering
selectable ARGB.

**Comment by carvalho2707** [comment]
I have the same opinion. At least for this won't be an option due to the lack of transparent options

**Comment by Blankeer** [comment]
Thanks to the big brother！ 🍺
