### ISSUE TITLE
attachAlphaSlideBar property cannot be configured via preferences XML 

### ISSUE THREAD

**Issue by danbrough** [skydoves/ColorPickerPreference#20]
I'd like to be able to disable the alpha slidebar in my preferences xml.

There isn't a style attribute to configure it.

**Comment by skydoves** [comment]
Hi, @danbrough.
Sorry for the late reply.
You can customize the `attachAlphaSlideBar` on the XML in the new release `2.0.1`.
Thank you for your issue :)
