### ISSUE TITLE
Set color programatically

### ISSUE THREAD

**Issue by MickeyKnox** [skydoves/ColorPickerPreference#23]
I have a ColorPickerPreference and I would like to set a color to it programatically. Unfortunately, I did not find an option to do so.

I tried to set the new color via SharedPreferences.Editor; this basically works, but the color preview is not updated. (After closing the Preferences and navigating back to them the color preview is updated, of course.)

What I'm trying to do is to reset the color to it's default value and the Preference to do so is right below the ColorPickerPreference.

**Comment by skydoves** [comment]
Hi,
I'm not sure but you can implement it using the below way.

- Don't set any preference name (key in the XML).
- Use `app:default_color` attribute in the XML or call `setInitialColor` method manually.
