### ISSUE TITLE
How selected color when dragging is Stopped by user .

### ISSUE THREAD

**Issue by DhiruServer** [skydoves/ColorPickerPreference#9]
I need to call some api as per our requirements  ,i using 
```

colorPickerView.setColorListener(new ColorListener() {
            @Override
            public void onColorSelected(ColorEnvelope colorEnvelope) {
                //LinearLayout linearLayout = findViewById(R.id.linearLayout);
                //linearLayout.setBackgroundColor(colorEnvelope.getColor())

                int rr [] = colorEnvelope.getColorRGB();
                 Log.i("Print","Color: "+rr);
            }
        });
```

But it is calling many time when i drag the pointer ,it's kind of live feed . but 
i want the color selected value when the user left dragging  , in this way we have restrict unnecessary api call .

Please help me

**Comment by skydoves** [comment]
@DhiruServer 
Hello!,
then would use this method?
```java
.setACTION_UP(true)
```
This method makes the listener be invoked when ACTION_UP action.
